.circleci/config.yml, .gitignore, Makefile
- Closes #84 
Improves maintainability!  Uses coverage.py to run our test suite and compare it to our src directory to find un-covered features. Uploads the report as an interactive html to CircleCI artifacts.
In CircleCI, under a test workflow, go to the Artifacts tab and find the [htmlcov/index.html](https://output.circle-artifacts.com/output/job/ff865a0e-797d-4482-998f-e33a1ef90b7d/artifacts/0/htmlcov/index.html) for code coverage. It's interactive to find different functions in files we haven't covered in testing!
=> maint: add coverage report html to circleci artifacts

.circleci/config.yml, .gitignore, DEVELOPING.md, Makefile, examples/hello-world/Dockerfile, examples/hello-world/app.py, examples/hello-world/poetry.lock, examples/hello-world/pyproject.toml, smoke-tests/docker-compose.yml, smoke-tests/smoke-sdk-grpc.bats, smoke-tests/smoke-sdk-http.bats, smoke-tests/test_helpers/utilities.bash
- updates #73 
- updates #74 
- expands on the regular python example app 
- adds http and grpc smoke tests for regular python example app
- adds notes around local testing and running the apps in docker
`make smoke-sdk` runs and succeeds; artifacts are published with expected contents [in circle](https://app.circleci.com/pipelines/github/honeycombio/honeycomb-opentelemetry-python/236/workflows/eadaedbb-589c-4314-9322-9ea3ffb2e839/jobs/1282/artifacts)
=> maint: smoke test python app

src/honeycomb/opentelemetry/options.py, tests/test_options.py
- Closes #98 
Parses HONEYCOMB_API_ENDPOINT as an option. 
In the hello-world-flask app, try something like `DEBUG=TRUE HONEYCOMB_API_ENDPOINT=http://collector:4317 OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://custom.metrics:666 poetry run opentelemetry-instrument flask run` to see the expected endpoint resolution:
```
'traces_exporter_protocol': 'http/protobuf', 
'metrics_exporter_protocol': 'http/protobuf',
'endpoint': 'http://collector:4317', 
'traces_endpoint': 'http://collector:4317/v1/traces', 
'metrics_endpoint': 'http://custom.metrics:666', 
// not expected to append /v1/metrics for http protocol w/ specifically declared OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
```
=> feat: allow HONEYCOMB_API_ENDPOINT as an Option parsed as an environment variable

poetry.lock, pyproject.toml
Reverts honeycombio/honeycomb-opentelemetry-python#70
We have some fuckery with the dockerizing of the flask app and upgrading dependencies in an open PR. This bump is causing some merge conflicts and it seems easiest to revert and change separately.
=> maint: Revert "maint(deps-dev): bump pylint from 2.15.10 to 2.16.0"

src/honeycomb/opentelemetry/sampler.py, tests/test_sampler.py
- Closes #97 
- Move from Parent-based DEFAULT_ON, DEFAULT_OFF to ALWAYS_OFF, ALWAYS_ON, TraceIdRatioBased Sampling. 
- Update documentation to reflect this change.
=> feat: move away from a ParentBased sampling approach.

DEVELOPING.md, Makefile, README.md, examples/README.md, examples/hello-world-flask/README.md, examples/hello-world-flask/app.py, examples/hello-world/README.md, examples/hello-world/app.py
- Closes #57 
- Closes #77 
- Created an examples overview 
- Comments to smoke tests re: testing both configure_opentelemetry() and opentelemetry_instrument
- Moved example development notes to developing.md
- Left additional breadcrumbs for others to use the smoke-test docker-compose for running examples with collector should they so choose
All the links in the readme's work.
Finding information about example usage is clear.
It's clear there are two ways to use the distro: configure_opentelemetry() or opentelemetry_instrument
Note: This is probably best reviewed by viewing the readme's in the [repo view](https://github.com/honeycombio/honeycomb-opentelemetry-python/tree/emash-config-vs-command) rather than the .md diffs :)
=> doc: clarify SDK configuration options (command vs function) and final developing.md & readme.md audits

smoke-tests/smoke-sdk-grpc-flask.bats, smoke-tests/smoke-sdk-http-flask.bats
- Updates #109 
It seems like this is indeed working, and more digging should be done to figure out how we end up in a state where it doesn't work. This smoke test should at least give some confidence about it working in a container - specifically, an environment separate from our own computers.
- Add tests to smoke tests for auto-instrumented spans for flask
Smoke tests should pass with the auto-instrumented flask spans being tested
=> maint: add tests for auto instrumentation

.github/workflows/auto-merge.yml
- Lots of dependabots; auto-merging some subset of these may help ease some of the pain 
Add dependabot auto-merge workflow.
Current state of this file:
- `github.actor == 'dependabot[bot]'` means only run for PRs authored by Dependabot
- `(steps.metadata.outputs.dependency-type, 'direct:development')` means only run on dev dependencies
- `steps.metadata.outputs.update-type == 'version-update:semver-patch'` means only run for patch updates
- `gh pr review --approve "$PR_URL"` means approve PRs that match the above conditions
- `gh pr merge --auto --merge "$PR_URL"` means merge PRs that match the above conditions
After merging... In Insights / Dependency Graph / Dependabot, check for updates (or wait until the next weekly run). Any dev dependencies that have a patch update available should …
=> maint: add auto-merge dependabot workflow

OSSMETADATA
- Lifecycle badge still showed experimental; should be active now that this is a published beta package.
- change experimental lifecycle status to active in `OSSMETADATA`, which gets pulled into the readme for the badge
after merge, refresh readme to see active badge
=> maint: change experimental badge to active

.github/workflows/auto-merge.yml
- previous attempts to auto-merge dev dependencies [failed](https://github.com/honeycombio/honeycomb-opentelemetry-python/actions/runs/4585202481/jobs/8097205347?pr=118) merge
- update `--merge` flag to `--squash` [flag](https://cli.github.com/manual/gh_pr_merge)
next dependabot should successfully auto-merge a passing dev patch update
=> maint: use squash merge for dependabot auto-merge

CHANGELOG.md, README.md, pyproject.toml
Prepares the v0.2.0b0 release.
- Updates version to 0.2.0b0
- Adds changelog entry
- Updates README to show OTel SDK version used to build with
=> rel: Prepare v0.2.0b0 release

src/honeycomb/opentelemetry/distro.py, src/honeycomb/opentelemetry/sampler.py
Importing the honeycomb module throws these warnings.
```
WARNING:honeycomb.opentelemetry.options:Missing API key. Specify either HONEYCOMB_API_KEY environment variable or apikey in the optionsparameter.
WARNING:honeycomb.opentelemetry.options:Missing service name. Specify either OTEL_SERVICE_NAME environment variable or service_name in the options parameter. If left unset, this will show up in Honeycomb as unknown_service:python
```
This side effect shouldn't happen at import time. I changed to use `None` as the default value, and handle the value when the function is invoked.
This can be verified by running the hello world example in the project, or this simpler reproducible snippet:
```python
import logging
logging.basicConfig(level=logging.DEBUG)
from honeycomb.opentelemetry.options …
```
=> Don't init HoneycombOptions on import

.circleci/config.yml, smoke-tests/docker-compose.yml
Adds nightly test jobs and upgrades ubuntu and the collector version for smoke tests. It seems like this also fixes the failed smoke test issues we're seeing on main.
- Closes #145 
- Added `nightly` workflow to CircleCI config
- Upgraded Ubuntu for smoke tests
- Upgraded collector version for smoke tests
- [Nightly build runs tests](https://app.circleci.com/pipelines/github/honeycombio/honeycomb-opentelemetry-python/388/workflows/6b3f9ebe-f150-4abb-a524-238d214668e3)
- Not sure how to test the cron job will work exactly before we merge this in, but it is the same as on our other repos so I'm fairly confident it will be the same.
=> maint: Add nightly tests job

.github/dependabot.yml
- updates https://github.com/honeycombio/telemetry-team/issues/487
groups are in beta and allow configuring dependabot to open a single pr for grouped dependencies
trying grouping testing dependencies together, so that a passing test suite is enough to merge that group
grouping otel together, because more often than not we need to update all otel versions
dependabot continues to run and we get fewer PRs
=> maint: try using dependabot groups

CHANGELOG.md, README.md, pyproject.toml
=> rel: prepare release 0.2.2b0

Makefile
- Closes #69
sets shell to bash to fix shell builtin behaviour
run `make test` with a disruptive environment variable that starts with `HONEYCOMB_` or `OTEL_` set
=> fix: set shell to `bash` in `Makefile` to enable `unset`

src/honeycomb/opentelemetry/options.py, tests/test_options.py
If an HTTP endpoint for traces or metrics already includes the signal path (eg /v1/traces or /v1/metrics), the path is added a second time (eg `http://somewhere.com/v1/traces` becomes `http://somewhere.com/v1/traces/v1/traces`).
The path should only be added if it doesn't already exist.
- Closes #155 
- Update options.get_traces_endpoint and options.get_metrics_endpoint to check if the endpoint already ends with the signal path before adding it
- Add tests to verify behaviour
You can now use an endpoint with a signal path and the signal path won't be added twice.
=> maint: Don’t append OTLP signal paths if already present

Makefile
- PyPI now requires API tokens instead of username/password for publishing packages which ([caused our last publish attempt to fail](https://app.circleci.com/pipelines/github/honeycombio/honeycomb-opentelemetry-python/655/workflows/2e762044-db51-4917-983b-0b3f637187b4/jobs/4412))
- Update `make publish` to use new PyPI API token ([see PyPI docs here](https://pypi.org/help/#apitoken))
Next publish attempt should be successful! Ran this command locally and it succeeded in showing this syntax is correct.
=> maint: update publish target for PyPI

examples/hello-world-django/README.md
Fixes a couple of typos in the Django example added in the following PR:
- #176 
- Fix typos
- Update run command to match previous example
Django example doesn't contain typos and commands execute as expected.
=> docs: Fix django example typos

CHANGELOG.md, pyproject.toml
- The previous tag used a commit from the release prep PR instead of main. Retagging to ensure we have the commit from main as the latest published release.
- update changelog
- update version
=> rel: prep release v0.4.2b0
